# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dining_hall_tracker_development

test:
  <<: *default
  database: dining_hall_tracker_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV["RENDER_DB_NAME"] %>
  username: <%= ENV["RENDER_DB_USER"] %>
  password: <%= ENV["RENDER_DB_PASSWORD"] %>
  host: <%= ENV["RENDER_DB_HOST"] %>
  port: <%= ENV["RENDER_DB_PORT"] %>