# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dining_hall_tracker_development

test:
  <<: *default
  database: dining_hall_tracker_test

production:
  <<: *default
  database: dining_hall_tracker_production
  username: dining_hall_tracker
  password: <%= ENV["DINING_HALL_TRACKER_DATABASE_PASSWORD"] %>